const MUNICIPIO='Barão de Melgaço', CODE='5101605';
const CLIMATE_URL='https://raw.githubusercontent.com/ernandes-sobreira/clima-pantanal/main/data/clima_pantanal.csv';
const META={rain:['Precipitação total','mm'],temp:['Temperatura média','°C'],tmax:['Temperatura máxima','°C'],tmin:['Temperatura mínima','°C'],humidity:['Umidade relativa','%'],heat_index:['Índice de calor','°C']};
let climate=[],fire=[],impacts=[],types=[],joined=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function csvLine(line){let a=[],c='',q=false;for(let i=0;i<line.length;i++){let x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++;}else q=!q;}else if(x===','&&!q){a.push(c);c='';}else c+=x;}a.push(c);return a;}
function parseCSV(t){let l=t.replace(/^\uFEFF/,'').trim().split(/\r?\n/).filter(Boolean),h=csvLine(l[0]);return l.slice(1).map(r=>{let v=csvLine(r),o={};h.forEach((k,i)=>o[k.trim()]=(v[i]||'').trim());return o;});}
const num=v=>{let n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:NaN};
async function getCSV(u){let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);return parseCSV(await r.text())}
function mean(a){let x=a.filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:NaN}
function sd(a){let x=a.filter(Number.isFinite),m=mean(x);return x.length>1?Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1)):NaN}
function median(a){let x=a.filter(Number.isFinite).slice().sort((a,b)=>a-b),m=Math.floor(x.length/2);return !x.length?NaN:x.length%2?x[m]:(x[m-1]+x[m])/2}
function pearson(a,b){let p=a.map((x,i)=>[x,b[i]]).filter(z=>z.every(Number.isFinite));if(p.length<3)return NaN;let x=p.map(z=>z[0]),y=p.map(z=>z[1]),mx=mean(x),my=mean(y);let n=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0),dx=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)),dy=Math.sqrt(y.reduce((s,v)=>s+(v-my)**2,0));return dx&&dy?n/(dx*dy):NaN}
function ranks(a){let ix=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),r=Array(a.length),i=0;while(i<ix.length){let j=i;while(j+1<ix.length&&ix[j+1].v===ix[i].v)j++;let rr=(i+j+2)/2;for(let k=i;k<=j;k++)r[ix[k].i]=rr;i=j+1}return r}
function spearman(a,b){let p=a.map((x,i)=>[x,b[i]]).filter(z=>z.every(Number.isFinite));return p.length<3?NaN:pearson(ranks(p.map(z=>z[0])),ranks(p.map(z=>z[1]))) }
function reg(x,y){let p=x.map((v,i)=>[v,y[i]]).filter(z=>z.every(Number.isFinite));if(p.length<2)return{slope:NaN,intercept:NaN,r2:NaN,n:p.length};let xs=p.map(z=>z[0]),ys=p.map(z=>z[1]),mx=mean(xs),my=mean(ys),sxx=xs.reduce((s,v)=>s+(v-mx)**2,0),sxy=xs.reduce((s,v,i)=>s+(v-mx)*(ys[i]-my),0),slope=sxy/sxx,intercept=my-slope*mx,pred=xs.map(v=>intercept+slope*v),sst=ys.reduce((s,v)=>s+(v-my)**2,0),sse=ys.reduce((s,v,i)=>s+(v-pred[i])**2,0);return{slope,intercept,r2:sst?1-sse/sst:0,n:p.length}}
function erf(x){let s=x>=0?1:-1;x=Math.abs(x);let t=1/(1+.3275911*x);return s*(1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t)*Math.exp(-x*x))}
function mk(y){let v=y.filter(Number.isFinite),n=v.length,S=0;for(let i=0;i<n-1;i++)for(let j=i+1;j<n;j++)S+=Math.sign(v[j]-v[i]);let c={};v.forEach(x=>c[x]=(c[x]||0)+1);let tie=Object.values(c).reduce((s,t)=>s+t*(t-1)*(2*t+5),0),vs=(n*(n-1)*(2*n+5)-tie)/18,z=S>0?(S-1)/Math.sqrt(vs):S<0?(S+1)/Math.sqrt(vs):0,p=2*(1-.5*(1+erf(Math.abs(z)/Math.sqrt(2))));return{tau:S/(n*(n-1)/2),p,z}}
function sen(x,y){let p=x.map((v,i)=>[v,y[i]]).filter(z=>z.every(Number.isFinite)),s=[];for(let i=0;i<p.length-1;i++)for(let j=i+1;j<p.length;j++)if(p[j][0]!==p[i][0])s.push((p[j][1]-p[i][1])/(p[j][0]-p[i][0]));return median(s)}
const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const pfmt=p=>!Number.isFinite(p)?'—':p<.001?'< 0,001':fmt(p,3);
function canvas(el){let c=typeof el==='string'?$(el):el,box=c.parentElement.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(320,box.width),h=Math.max(260,box.height||320);c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';let x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);return{x,w,h}}
function nice(v){if(!v)return 1;let p=10**Math.floor(Math.log10(v)),n=v/p;return (n<=1?1:n<=2?2:n<=5?5:10)*p}
function axes(ctx,w,h,minY,maxY,labels){let L=58,R=16,T=18,B=44,pw=w-L-R,ph=h-T-B;ctx.strokeStyle='#d9dedb';ctx.fillStyle='#627079';ctx.font='12px system-ui';ctx.lineWidth=1;let step=nice((maxY-minY)/4),lo=Math.floor(minY/step)*step,hi=Math.ceil(maxY/step)*step;if(lo===hi)hi=lo+step;for(let y=lo;y<=hi+.0001;y+=step){let py=T+ph*(1-(y-lo)/(hi-lo));ctx.beginPath();ctx.moveTo(L,py);ctx.lineTo(w-R,py);ctx.stroke();ctx.fillText(Math.abs(y)>=1000?Math.round(y).toLocaleString('pt-BR'):fmt(y,1),5,py+4)};let every=Math.ceil(labels.length/8);labels.forEach((lab,i)=>{if(i%every===0||i===labels.length-1){let px=L+pw*(i/Math.max(1,labels.length-1));ctx.fillText(String(lab),px-12,h-16)}});return{L,R,T,B,pw,ph,lo,hi}}
function lineChart(sel,labels,vals,opt={}){let {x,w,h}=canvas(sel),min=Math.min(...vals),max=Math.max(...vals);if(opt.zero)min=0;let a=axes(x,w,h,min,max,labels),pts=vals.map((v,i)=>[a.L+a.pw*i/Math.max(1,vals.length-1),a.T+a.ph*(1-(v-a.lo)/(a.hi-a.lo))]);x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.strokeStyle=opt.color||'#d95f37';x.lineWidth=2.5;x.stroke();x.fillStyle=opt.color||'#d95f37';pts.forEach(p=>{x.beginPath();x.arc(p[0],p[1],3,0,Math.PI*2);x.fill()});if(opt.trend){let rr=reg(labels.map(Number),vals),v0=rr.intercept+rr.slope*Number(labels[0]),v1=rr.intercept+rr.slope*Number(labels.at(-1)),py=v=>a.T+a.ph*(1-(v-a.lo)/(a.hi-a.lo));x.setLineDash([7,5]);x.strokeStyle='#152733';x.lineWidth=1.5;x.beginPath();x.moveTo(a.L,py(v0));x.lineTo(a.L+a.pw,py(v1));x.stroke();x.setLineDash([])}}
function impactChart(){let {x,w,h}=canvas('#impactChart'),labels=impacts.map(d=>d.ano),ev=impacts.map(d=>d.eventos_desastre),af=impacts.map(d=>d.total_afetados),L=58,R=54,T=18,B=44,pw=w-L-R,ph=h-T-B,maxE=Math.max(...ev,1),maxA=Math.max(...af,1),bw=Math.max(3,pw/labels.length*.5);x.font='12px system-ui';x.strokeStyle='#e0e4e0';for(let j=0;j<=4;j++){let py=T+ph*j/4;x.beginPath();x.moveTo(L,py);x.lineTo(w-R,py);x.stroke();x.fillStyle='#627079';x.fillText(fmt(maxE*(1-j/4),0),8,py+4);x.fillText(Math.round(maxA*(1-j/4)).toLocaleString('pt-BR'),w-R+8,py+4)}ev.forEach((v,i)=>{let px=L+pw*i/(labels.length-1);x.fillStyle='rgba(29,118,111,.75)';x.fillRect(px-bw/2,T+ph*(1-v/maxE),bw,ph*v/maxE)});x.strokeStyle='#d29a2d';x.lineWidth=2.3;x.beginPath();af.forEach((v,i)=>{let px=L+pw*i/(labels.length-1),py=T+ph*(1-v/maxA);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();let every=Math.ceil(labels.length/8);labels.forEach((v,i)=>{if(i%every===0||i===labels.length-1){x.fillStyle='#627079';x.fillText(v,L+pw*i/(labels.length-1)-12,h-16)}})}
function scatter(sel,rows,key){let xvals=rows.map(d=>d[key]),yvals=rows.map(d=>d.focos_calor),{x,w,h}=canvas(sel),L=58,R=16,T=18,B=48,pw=w-L-R,ph=h-T-B,minX=Math.min(...xvals),maxX=Math.max(...xvals),maxY=Math.max(...yvals),rx=v=>L+pw*(v-minX)/(maxX-minX||1),ry=v=>T+ph*(1-v/(maxY||1));x.strokeStyle='#d9dedb';x.font='12px system-ui';x.fillStyle='#627079';for(let j=0;j<=4;j++){let py=T+ph*j/4;x.beginPath();x.moveTo(L,py);x.lineTo(w-R,py);x.stroke();x.fillText(Math.round(maxY*(1-j/4)).toLocaleString('pt-BR'),5,py+4)}for(let j=0;j<=4;j++){let v=minX+(maxX-minX)*j/4;x.fillText(fmt(v,1),rx(v)-10,h-18)}x.fillStyle='#d95f37';rows.forEach(d=>{x.beginPath();x.arc(rx(d[key]),ry(d.focos_calor),5,0,Math.PI*2);x.fill()});let rr=reg(xvals,yvals),xx=[minX,maxX];x.strokeStyle='#152733';x.setLineDash([7,5]);x.beginPath();xx.forEach((v,i)=>{let p=[rx(v),ry(rr.intercept+rr.slope*v)];i?x.lineTo(...p):x.moveTo(...p)});x.stroke();x.setLineDash([])}
function normalizeClimate(rows){return rows.map(r=>({code:String(r.CD_MUN||r.codigo_ibge||r.COD_IBGE||'').replace(/\.0$/,''),name:r.NM_MUN||r.municipio||'',year:num(r.ANO||r.ano||r.YEAR),rain:num(r.PRECIPITACAO_TOTAL_MM),temp:num(r.TEMPERATURA_MEDIA_C),tmax:num(r.TEMPERATURA_MAX_C),tmin:num(r.TEMPERATURA_MIN_C),humidity:num(r['UMIDADE_RELATIVA_MEDIA_%']),heat_index:num(r.INDICE_CALOR_MEDIO)})).filter(r=>r.code===CODE&&Number.isFinite(r.year)).sort((a,b)=>a.year-b.year)}
function setupTabs(){$$('.tab-btn').forEach(b=>{b.onclick=()=>{$$('.tab-btn').forEach(x=>x.classList.remove('active'));$$('.panel-section').forEach(x=>x.classList.remove('active-section'));b.classList.add('active');$('#'+b.dataset.target).classList.add('active-section');setTimeout(renderVisible,30);};});}
function renderFire(){lineChart('#fireChart',fire.map(d=>d.ano),fire.map(d=>d.focos_calor),{zero:true,trend:true});let m=mk(fire.map(d=>d.focos_calor)),s=sen(fire.map(d=>d.ano),fire.map(d=>d.focos_calor));$('#senFire').textContent=(s>=0?'+':'')+fmt(s,1);$('#mkFireText').textContent=`Mann–Kendall: τ = ${fmt(m.tau,3)}, p = ${pfmt(m.p)}. ${m.p<.05?'Tendência monotônica significativa.':'Sem tendência monotônica significativa.'}`}
function renderTypes(){let g={};types.forEach(d=>g[d.descricao_tipologia]=(g[d.descricao_tipologia]||0)+d.eventos);let a=Object.entries(g).sort((x,y)=>y[1]-x[1]),mx=Math.max(...a.map(x=>x[1]));$('#typeBars').innerHTML=a.map(([k,v])=>`<div class="type-row"><span>${k}</span><div class="bar-track"><div class="bar-fill" style="width:${v/mx*100}%"></div></div><strong>${v}</strong></div>`).join('')}
function renderClimate(){if(!climate.length)return;let key=$('#climateVariable').value,d=climate.filter(z=>Number.isFinite(z[key])),vals=d.map(z=>z[key]),m=mk(vals),s=sen(d.map(z=>z.year),vals),rr=reg(d.map(z=>z.year),vals),[lab,u]=META[key];$('#climateChartTitle').textContent=lab;lineChart('#climateChart',d.map(z=>z.year),vals,{trend:true,color:'#1d766f'});$('#climateStats').innerHTML=`<span class="stat-pill">Média <strong>${fmt(mean(vals),1)} ${u}</strong></span><span class="stat-pill">Sen <strong>${s>=0?'+':''}${fmt(s,3)} ${u}/ano</strong></span><span class="stat-pill">MK τ <strong>${fmt(m.tau,3)}</strong></span><span class="stat-pill">p <strong>${pfmt(m.p)}</strong></span><span class="stat-pill">R² <strong>${fmt(rr.r2,3)}</strong></span>`}
function renderRelations(){if(!joined.length||!climate.length)return;let key=$('#scatterVariable').value,d=joined.filter(z=>Number.isFinite(z[key])),r=pearson(d.map(z=>z[key]),d.map(z=>z.focos_calor)),rho=spearman(d.map(z=>z[key]),d.map(z=>z.focos_calor)),rr=reg(d.map(z=>z[key]),d.map(z=>z.focos_calor));scatter('#scatterChart',d,key);$('#scatterStats').innerHTML=`<span class="stat-pill">Pearson r <strong>${fmt(r,3)}</strong></span><span class="stat-pill">Spearman ρ <strong>${fmt(rho,3)}</strong></span><span class="stat-pill">R² <strong>${fmt(rr.r2,3)}</strong></span><span class="stat-pill">n <strong>${d.length}</strong></span>`;let ar=Object.keys(META).map(k=>({k,r:pearson(joined.map(d=>d[k]),joined.map(d=>d.focos_calor))})).filter(z=>Number.isFinite(z.r)).sort((a,b)=>Math.abs(b.r)-Math.abs(a.r));$('#correlationRanking').innerHTML=ar.map(z=>`<div class="rank-row"><span>${META[z.k][0]}</span><div class="rank-track"><div class="rank-fill" style="width:${Math.abs(z.r)*100}%"></div></div><span class="rank-value">${z.r>0?'+':''}${fmt(z.r,2)}</span></div>`).join('');renderMatrix(ar.map(z=>z.k));renderModel();renderPCA();renderFindings(ar)}
function renderMatrix(keys){let ks=['fire',...keys],names={fire:'Focos',...Object.fromEntries(Object.entries(META).map(([k,v])=>[k,v[0].replace('Temperatura','T.').replace('Precipitação total','Precip.').replace('Umidade relativa','Umidade').replace('Índice de calor','I. calor')]))};let rows=joined.map(d=>({...d,fire:d.focos_calor}));let html='<table class="corr-table"><tr><th></th>'+ks.map(k=>`<th>${names[k]}</th>`).join('')+'</tr>';ks.forEach(a=>{html+=`<tr><th>${names[a]}</th>`+ks.map(b=>{let r=pearson(rows.map(d=>d[a]),rows.map(d=>d[b]));return `<td title="r=${fmt(r,3)}">${fmt(r,2)}</td>`}).join('')+'</tr>'});$('#corrMatrix').innerHTML=html+'</table>'}
function solve(A,b){let n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(M[j][i])>Math.abs(M[p][i]))p=j;[M[i],M[p]]=[M[p],M[i]];if(Math.abs(M[i][i])<1e-10)return null;let q=M[i][i];for(let k=i;k<=n;k++)M[i][k]/=q;for(let j=0;j<n;j++)if(j!==i){let f=M[j][i];for(let k=i;k<=n;k++)M[j][k]-=f*M[i][k]}}return M.map(r=>r[n])}
function renderModel(){let ks=['rain','tmax','humidity'],d=joined.filter(r=>ks.every(k=>Number.isFinite(r[k])));if(!d.length)return;let X=d.map(r=>[1,...ks.map(k=>(r[k]-mean(d.map(z=>z[k])))/sd(d.map(z=>z[k])))]),y=d.map(r=>Math.log1p(r.focos_calor)),p=X[0].length,A=Array.from({length:p},()=>Array(p).fill(0)),b=Array(p).fill(0);X.forEach((r,i)=>{for(let j=0;j<p;j++){b[j]+=r[j]*y[i];for(let k=0;k<p;k++)A[j][k]+=r[j]*r[k]}});let beta=solve(A,b);if(!beta){$('#multiReg').innerHTML='Modelo indisponível';return}let pred=X.map(r=>r.reduce((s,v,i)=>s+v*beta[i],0)),my=mean(y),r2=1-y.reduce((s,v,i)=>s+(v-pred[i])**2,0)/y.reduce((s,v)=>s+(v-my)**2,0);$('#multiReg').innerHTML=`<div class="big-stat">R² = ${fmt(r2,3)}</div><p>Resposta: <strong>log(1 + focos)</strong>. Preditores padronizados:</p>${ks.map((k,i)=>`<div class="coef"><span>${META[k][0]}</span><strong>${beta[i+1]>=0?'+':''}${fmt(beta[i+1],3)}</strong></div>`).join('')}<small>Modelo exploratório; n=${d.length}. Não interpretar coeficiente isolado como causal.</small>`}
function power(C){let n=C.length,v=Array(n).fill(1/Math.sqrt(n));for(let it=0;it<100;it++){let w=C.map(r=>r.reduce((s,x,j)=>s+x*v[j],0)),norm=Math.sqrt(w.reduce((s,x)=>s+x*x,0));v=w.map(x=>x/norm)}let Cv=C.map(r=>r.reduce((s,x,j)=>s+x*v[j],0)),val=v.reduce((s,x,i)=>s+x*Cv[i],0);return{v,val}}
function renderPCA(){let ks=['rain','temp','tmax','tmin','humidity','heat_index','focos_calor'],d=joined.filter(r=>ks.every(k=>Number.isFinite(r[k])));if(d.length<5)return;let Z=d.map(r=>ks.map(k=>(r[k]-mean(d.map(z=>z[k])))/sd(d.map(z=>z[k])))),p=ks.length,C=Array.from({length:p},(_,i)=>Array.from({length:p},(_,j)=>Z.reduce((s,r)=>s+r[i]*r[j],0)/(Z.length-1))),e1=power(C),D=C.map((r,i)=>r.map((x,j)=>x-e1.val*e1.v[i]*e1.v[j])),e2=power(D),scores=Z.map(r=>({pc1:r.reduce((s,x,i)=>s+x*e1.v[i],0),pc2:r.reduce((s,x,i)=>s+x*e2.v[i],0)})),tot=C.reduce((s,r,i)=>s+r[i],0),p1=e1.val/tot*100,p2=e2.val/tot*100;let {x,w,h}=canvas('#pcaChart'),L=46,R=16,T=18,B=42,pw=w-L-R,ph=h-T-B,xs=scores.map(s=>s.pc1),ys=scores.map(s=>s.pc2),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),rx=v=>L+pw*(v-xmin)/(xmax-xmin||1),ry=v=>T+ph*(1-(v-ymin)/(ymax-ymin||1));x.strokeStyle='#d9dedb';x.beginPath();x.moveTo(rx(0),T);x.lineTo(rx(0),T+ph);x.moveTo(L,ry(0));x.lineTo(L+pw,ry(0));x.stroke();x.font='11px system-ui';scores.forEach((s,i)=>{x.fillStyle='#1d766f';x.beginPath();x.arc(rx(s.pc1),ry(s.pc2),4,0,Math.PI*2);x.fill();if(d[i].year===2020||d[i].year===2024){x.fillStyle='#152733';x.fillText(d[i].year,rx(s.pc1)+5,ry(s.pc2)-5)}});$('#pcaInfo').innerHTML=`<span class="stat-pill">PC1 <strong>${fmt(p1,1)}%</strong></span><span class="stat-pill">PC2 <strong>${fmt(p2,1)}%</strong></span><span class="stat-pill">Acumulado <strong>${fmt(p1+p2,1)}%</strong></span>`;let names={...Object.fromEntries(Object.entries(META).map(([k,v])=>[k,v[0]])),focos_calor:'Focos de calor'};$('#pcaLoadings').innerHTML='<table class="corr-table"><tr><th>Variável</th><th>PC1</th><th>PC2</th></tr>'+ks.map((k,i)=>`<tr><td>${names[k]}</td><td>${fmt(e1.v[i],3)}</td><td>${fmt(e2.v[i],3)}</td></tr>`).join('')+'</table>'}
function renderFindings(ar=[]){let host=$('#mainFindings');if(!host){host=document.createElement('article');host.id='mainFindings';host.className='card full-card findings-card';$('#visao .grid-2').after(host)}let top=ar[0],rEv=pearson(joined.map(d=>d.focos_calor),joined.map(d=>d.eventos_desastre)),rAf=pearson(joined.map(d=>d.focos_calor),joined.map(d=>d.total_afetados)),peak=fire.slice().sort((a,b)=>b.focos_calor-a.focos_calor)[0],recent=fire.filter(d=>d.ano>=2016),old=fire.filter(d=>d.ano<2016),clim=top?`<b>Maior associação climática disponível:</b> ${META[top.k][0]}, r=${top.r>=0?'+':''}${fmt(top.r,2)} com focos.`:'<b>Relações climáticas:</b> serão exibidas assim que a série climática carregar.';host.innerHTML=`<div class="card-head"><div><span class="tag">SÍNTESE</span><h3>Principais achados</h3></div></div><div class="finding-grid"><div><strong>1</strong><p><b>2020 é o maior pico de fogo:</b> ${peak.focos_calor.toLocaleString('pt-BR')} focos.</p></div><div><strong>2</strong><p><b>O período recente é mais intenso:</b> média de ${fmt(mean(recent.map(d=>d.focos_calor)),0)} focos/ano desde 2016 contra ${fmt(mean(old.map(d=>d.focos_calor)),0)} em 2003–2015.</p></div><div><strong>3</strong><p>${clim}</p></div><div><strong>4</strong><p><b>Focos × registros de desastre:</b> r=${fmt(rEv,2)}; focos × pessoas afetadas: r=${fmt(rAf,2)}. Associação descritiva, não causal.</p></div></div>`}
function renderVisible(){if($('#visao').classList.contains('active-section')){renderFire();impactChart()}if($('#clima').classList.contains('active-section'))renderClimate();if($('#relacoes').classList.contains('active-section'))renderRelations();if($('#estatistica').classList.contains('active-section'))renderRelations()}
async function init(){setupTabs();try{[fire,impacts,types]=await Promise.all([getCSV('data/focos_barao_2003_2024.csv'),getCSV('data/desastres_barao_1991_2024.csv'),getCSV('data/tipologias_barao.csv')]);fire=fire.map(d=>({ano:num(d.ano),focos_calor:num(d.focos_calor)}));impacts=impacts.map(d=>({ano:num(d.ano),eventos_desastre:num(d.eventos_desastre),total_afetados:num(d.total_afetados)}));types=types.map(d=>({...d,eventos:num(d.eventos)}));renderFire();impactChart();renderTypes();let im=new Map(impacts.map(d=>[d.ano,d]));joined=fire.map(f=>({...f,...(im.get(f.ano)||{eventos_desastre:0,total_afetados:0})}));renderFindings();}catch(e){console.error(e)}
try{climate=normalizeClimate(await getCSV(CLIMATE_URL));if(!climate.length)throw Error('município não encontrado');let fm=new Map(fire.map(d=>[d.ano,d])),im=new Map(impacts.map(d=>[d.ano,d]));joined=climate.filter(c=>fm.has(c.year)).map(c=>({...c,...fm.get(c.year),...(im.get(c.year)||{eventos_desastre:0,total_afetados:0})}));$('#climateNotice').className='notice success';$('#climateNotice').textContent=`Série climática carregada: ${climate[0].year}–${climate.at(-1).year} • ${climate.length} anos.`;$('#climatePeriod').innerHTML=`<strong>${climate[0].year}–${climate.at(-1).year}</strong><small>série climática</small>`;$('#kpiClimate').innerHTML=`<span>Clima</span><strong>${climate.length} anos</strong><small>precipitação, temperatura, umidade e índice de calor</small>`;renderClimate();renderRelations()}catch(e){console.warn(e);$('#climateNotice').className='notice error';$('#climateNotice').textContent='A série climática externa não pôde ser carregada agora. Os gráficos de fogo e impactos continuam disponíveis.'}
$('#climateVariable').onchange=renderClimate;$('#scatterVariable').onchange=renderRelations;window.addEventListener('resize',()=>setTimeout(renderVisible,80))}
document.addEventListener('DOMContentLoaded',init);