'use strict';
const CODE='5101605';
const CLIMATE_URL='https://raw.githubusercontent.com/ernandes-sobreira/clima-pantanal/main/data/clima_pantanal.csv';
const META={
 rain:{label:'Precipitação anual',unit:'mm',agg:'sum'},
 temp:{label:'Temperatura média',unit:'°C',agg:'mean'},
 tmax:{label:'Temperatura máxima média',unit:'°C',agg:'mean'},
 tmin:{label:'Temperatura mínima média',unit:'°C',agg:'mean'},
 humidity:{label:'Umidade relativa média',unit:'%',agg:'mean'},
 heat_index:{label:'Índice de calor médio',unit:'°C',agg:'mean'},
 heat_max:{label:'Índice de calor máximo',unit:'°C',agg:'max'}
};
let monthly=[],climate=[],fire=[],impacts=[],types=[],joined=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function parseNumber(v){const s=String(v??'').trim();if(!s)return NaN;const n=Number(s.replace(',','.'));return Number.isFinite(n)?n:NaN}
function splitCSV(line){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const head=splitCSV(lines[0]).map(x=>x.trim());return lines.slice(1).map(line=>{const vals=splitCSV(line);const o={};head.forEach((h,i)=>o[h]=(vals[i]??'').trim());return o})}
async function getCSV(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return parseCSV(await r.text())}
function mean(a){const x=a.filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:NaN}
function median(a){const x=a.filter(Number.isFinite).slice().sort((a,b)=>a-b);if(!x.length)return NaN;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function sd(a){const x=a.filter(Number.isFinite),m=mean(x);return x.length>1?Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1)):NaN}
function fmt(v,d=2){return Number.isFinite(v)?v.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—'}
function pfmt(p){return !Number.isFinite(p)?'—':p<.001?'< 0,001':fmt(p,3)}
function linReg(x,y){const p=x.map((v,i)=>[v,y[i]]).filter(z=>z.every(Number.isFinite));if(p.length<2)return{slope:NaN,intercept:NaN,r2:NaN,n:p.length};const xs=p.map(z=>z[0]),ys=p.map(z=>z[1]),mx=mean(xs),my=mean(ys),sxx=xs.reduce((s,v)=>s+(v-mx)**2,0),sxy=xs.reduce((s,v,i)=>s+(v-mx)*(ys[i]-my),0),slope=sxx?sxy/sxx:0,intercept=my-slope*mx,pred=xs.map(v=>intercept+slope*v),sst=ys.reduce((s,v)=>s+(v-my)**2,0),sse=ys.reduce((s,v,i)=>s+(v-pred[i])**2,0);return{slope,intercept,r2:sst?1-sse/sst:0,n:p.length}}
function pearson(a,b){const p=a.map((x,i)=>[x,b[i]]).filter(z=>z.every(Number.isFinite));if(p.length<3)return NaN;const x=p.map(z=>z[0]),y=p.map(z=>z[1]),mx=mean(x),my=mean(y),num=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0),dx=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)),dy=Math.sqrt(y.reduce((s,v)=>s+(v-my)**2,0));return dx&&dy?num/(dx*dy):NaN}
function ranks(a){const ix=a.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),r=Array(a.length);let i=0;while(i<ix.length){let j=i;while(j+1<ix.length&&ix[j+1].v===ix[i].v)j++;const rr=(i+j+2)/2;for(let k=i;k<=j;k++)r[ix[k].i]=rr;i=j+1}return r}
function spearman(a,b){const p=a.map((x,i)=>[x,b[i]]).filter(z=>z.every(Number.isFinite));return p.length<3?NaN:pearson(ranks(p.map(z=>z[0])),ranks(p.map(z=>z[1])))}
function erf(x){const sign=x>=0?1:-1;x=Math.abs(x);const t=1/(1+.3275911*x);return sign*(1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t)*Math.exp(-x*x))}
function normCDF(z){return .5*(1+erf(z/Math.sqrt(2)))}
function mannKendall(y){const v=y.filter(Number.isFinite),n=v.length;if(n<3)return{tau:NaN,p:NaN,z:NaN,n};let S=0;for(let i=0;i<n-1;i++)for(let j=i+1;j<n;j++)S+=Math.sign(v[j]-v[i]);const c=new Map();v.forEach(x=>c.set(x,(c.get(x)||0)+1));const tie=[...c.values()].reduce((s,t)=>s+t*(t-1)*(2*t+5),0),varS=(n*(n-1)*(2*n+5)-tie)/18,z=varS>0?(S>0?(S-1)/Math.sqrt(varS):S<0?(S+1)/Math.sqrt(varS):0):0,p=2*(1-normCDF(Math.abs(z)));return{tau:S/(n*(n-1)/2),p,z,n}}
function senSlope(x,y){const p=x.map((v,i)=>[v,y[i]]).filter(z=>z.every(Number.isFinite)),s=[];for(let i=0;i<p.length-1;i++)for(let j=i+1;j<p.length;j++)if(p[j][0]!==p[i][0])s.push((p[j][1]-p[i][1])/(p[j][0]-p[i][0]));return median(s)}
function normalizeMonthly(rows){return rows.map(r=>({
 code:String(r.CD_MUN??r.cd_mun??r.codigo_ibge??'').trim().replace(/\.0$/,''),
 name:String(r.NM_MUN??r.nm_mun??r.municipio??''),year:parseInt(r.year??r.ANO??'',10),month:parseInt(r.month??r.MES??'',10),
 rain:parseNumber(r.precip_sum_mm),temp:parseNumber(r.tmean_c),tmax:parseNumber(r.tmax_c),tmin:parseNumber(r.tmin_c),humidity:parseNumber(r.rh_mean_pct),heat_index:parseNumber(r.hi_mean_c),heat_max:parseNumber(r.hi_max_c)
 })).filter(r=>r.code===CODE&&Number.isFinite(r.year)&&r.year>1900&&r.year<2100&&Number.isFinite(r.month)&&r.month>=1&&r.month<=12)}
function aggregateAnnual(rows){const by=new Map();rows.forEach(r=>{if(!by.has(r.year))by.set(r.year,[]);by.get(r.year).push(r)});return [...by.entries()].sort((a,b)=>a[0]-b[0]).map(([year,rs])=>{const out={year,months:new Set(rs.map(r=>r.month)).size};for(const [key,m] of Object.entries(META)){const vals=rs.map(r=>r[key]).filter(Number.isFinite);out[key]=!vals.length?NaN:m.agg==='sum'?vals.reduce((s,v)=>s+v,0):m.agg==='max'?Math.max(...vals):mean(vals)}return out}).filter(r=>r.months>=10)}
function normalizeFire(rows){return rows.map(r=>({year:parseInt(r.ano,10),focos:parseNumber(r.focos_calor)})).filter(r=>Number.isFinite(r.year)&&Number.isFinite(r.focos)).sort((a,b)=>a.year-b.year)}
function normalizeImpacts(rows){return rows.map(r=>({year:parseInt(r.ano,10),events:parseNumber(r.eventos_desastre)||0,affected:parseNumber(r.total_afetados_fide_derivado)||0})).filter(r=>Number.isFinite(r.year)).sort((a,b)=>a.year-b.year)}
function normalizeTypes(rows){return rows.map(r=>({name:r.descricao_tipologia||'Outros',events:parseNumber(r.eventos)||0})).filter(r=>r.events>0)}
function joinAnnual(){const fm=new Map(fire.map(d=>[d.year,d.focos]));joined=climate.filter(c=>fm.has(c.year)).map(c=>({...c,focos:fm.get(c.year),logfire:Math.log1p(fm.get(c.year))}))}
function setupCanvas(id){const c=$(id);if(!c)return null;const box=c.parentElement.getBoundingClientRect();if(box.width<30)return null;const dpr=Math.min(devicePixelRatio||1,2),w=box.width,h=box.height;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);c.style.width=w+'px';c.style.height=h+'px';const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.font='12px system-ui';x.lineCap='round';x.lineJoin='round';return{x,w,h}}
function scale(v,a,b,c,d){return c+(v-a)/(b-a||1)*(d-c)}
function drawLine(id,labels,vals,{color='#19756f',zero=false,trend=false}={}){const s=setupCanvas(id);if(!s)return;const {x,w,h}=s,L=58,R=18,T=18,B=44,pw=w-L-R,ph=h-T-B,finite=vals.filter(Number.isFinite);if(!finite.length){x.fillStyle='#68747d';x.fillText('Sem dados.',L,T+30);return}let lo=zero?0:Math.min(...finite),hi=Math.max(...finite);if(lo===hi){lo-=1;hi+=1}const pad=(hi-lo)*.08;lo=zero?0:lo-pad;hi+=pad;x.strokeStyle='#e0ddd5';x.fillStyle='#68747d';x.lineWidth=1;for(let j=0;j<=4;j++){const py=T+ph*j/4,v=hi-(hi-lo)*j/4;x.beginPath();x.moveTo(L,py);x.lineTo(w-R,py);x.stroke();x.fillText(Math.abs(v)>=1000?Math.round(v).toLocaleString('pt-BR'):fmt(v,1),5,py+4)}const every=Math.max(1,Math.ceil(labels.length/7));labels.forEach((lab,i)=>{if(i%every===0||i===labels.length-1)x.fillText(String(lab),scale(i,0,labels.length-1,L,w-R)-12,h-14)});const pts=vals.map((v,i)=>Number.isFinite(v)?[scale(i,0,labels.length-1,L,w-R),scale(v,lo,hi,T+ph,T)]:null).filter(Boolean);x.strokeStyle=color;x.lineWidth=2.5;x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.stroke();x.fillStyle=color;pts.forEach(p=>{x.beginPath();x.arc(p[0],p[1],3,0,Math.PI*2);x.fill()});if(trend){const rr=linReg(labels.map(Number),vals),y0=rr.intercept+rr.slope*Number(labels[0]),y1=rr.intercept+rr.slope*Number(labels.at(-1));x.strokeStyle='#102232';x.lineWidth=1.5;x.setLineDash([7,5]);x.beginPath();x.moveTo(L,scale(y0,lo,hi,T+ph,T));x.lineTo(w-R,scale(y1,lo,hi,T+ph,T));x.stroke();x.setLineDash([])}}
function drawImpact(){const s=setupCanvas('#impactChart');if(!s)return;const {x,w,h}=s,L=48,R=58,T=18,B=44,pw=w-L-R,ph=h-T-B,maxE=Math.max(1,...impacts.map(d=>d.events)),maxA=Math.max(1,...impacts.map(d=>d.affected)),bw=Math.max(3,pw/impacts.length*.55);x.strokeStyle='#e0ddd5';x.fillStyle='#68747d';for(let j=0;j<=4;j++){const py=T+ph*j/4;x.beginPath();x.moveTo(L,py);x.lineTo(w-R,py);x.stroke();x.fillText(fmt(maxE*(1-j/4),0),7,py+4);x.fillText(Math.round(maxA*(1-j/4)).toLocaleString('pt-BR'),w-R+5,py+4)}impacts.forEach((d,i)=>{const px=scale(i,0,impacts.length-1,L,w-R);x.fillStyle='rgba(25,117,111,.75)';const bh=ph*d.events/maxE;x.fillRect(px-bw/2,T+ph-bh,bw,bh)});x.strokeStyle='#c8942d';x.lineWidth=2.2;x.beginPath();impacts.forEach((d,i)=>{const px=scale(i,0,impacts.length-1,L,w-R),py=T+ph*(1-d.affected/maxA);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();const every=Math.max(1,Math.ceil(impacts.length/7));impacts.forEach((d,i)=>{if(i%every===0||i===impacts.length-1){x.fillStyle='#68747d';x.fillText(d.year,scale(i,0,impacts.length-1,L,w-R)-12,h-14)}})}
function drawScatter(id,rows,key){const s=setupCanvas(id);if(!s)return;const {x,w,h}=s,L=58,R=18,T=18,B=48,pw=w-L-R,ph=h-T-B,xv=rows.map(d=>d[key]),yv=rows.map(d=>d.focos),xmin=Math.min(...xv),xmax=Math.max(...xv),ymax=Math.max(...yv,1),rx=v=>scale(v,xmin,xmax,L,w-R),ry=v=>scale(v,0,ymax,T+ph,T);x.strokeStyle='#e0ddd5';x.fillStyle='#68747d';for(let j=0;j<=4;j++){const py=T+ph*j/4;x.beginPath();x.moveTo(L,py);x.lineTo(w-R,py);x.stroke();x.fillText(Math.round(ymax*(1-j/4)).toLocaleString('pt-BR'),5,py+4)}for(let j=0;j<=4;j++){const v=xmin+(xmax-xmin)*j/4;x.fillText(fmt(v,1),rx(v)-12,h-15)}x.fillStyle='#df5f36';rows.forEach(d=>{x.beginPath();x.arc(rx(d[key]),ry(d.focos),5,0,Math.PI*2);x.fill()});const rr=linReg(xv,yv);x.strokeStyle='#102232';x.setLineDash([7,5]);x.beginPath();x.moveTo(rx(xmin),ry(rr.intercept+rr.slope*xmin));x.lineTo(rx(xmax),ry(rr.intercept+rr.slope*xmax));x.stroke();x.setLineDash([])}
function drawPCA(scores,ev1,ev2){const s=setupCanvas('#pcaChart');if(!s)return;const {x,w,h}=s,L=46,R=18,T=18,B=48,pw=w-L-R,ph=h-T-B,xv=scores.map(d=>d.pc1),yv=scores.map(d=>d.pc2),xm=Math.max(...xv.map(Math.abs),1),ym=Math.max(...yv.map(Math.abs),1),rx=v=>scale(v,-xm,xm,L,w-R),ry=v=>scale(v,-ym,ym,T+ph,T);x.strokeStyle='#d4d6d2';x.beginPath();x.moveTo(rx(0),T);x.lineTo(rx(0),T+ph);x.stroke();x.beginPath();x.moveTo(L,ry(0));x.lineTo(w-R,ry(0));x.stroke();x.fillStyle='#68747d';x.fillText(`PC1 ${fmt(ev1,1)}%`,w/2-25,h-13);x.save();x.translate(13,h/2+25);x.rotate(-Math.PI/2);x.fillText(`PC2 ${fmt(ev2,1)}%`,0,0);x.restore();scores.forEach(d=>{const special=d.year===2020||d.year===2024;x.fillStyle=special?'#df5f36':'#19756f';x.beginPath();x.arc(rx(d.pc1),ry(d.pc2),special?6:4,0,Math.PI*2);x.fill();if(special){x.font='bold 12px system-ui';x.fillText(String(d.year),rx(d.pc1)+7,ry(d.pc2)-7);x.font='12px system-ui'}})}
function pills(items){return items.map(([k,v])=>`<span class="pill">${k}<strong>${v}</strong></span>`).join('')}
function renderFire(){drawLine('#fireChart',fire.map(d=>d.year),fire.map(d=>d.focos),{color:'#df5f36',zero:true,trend:true});const mk=mannKendall(fire.map(d=>d.focos)),sen=senSlope(fire.map(d=>d.year),fire.map(d=>d.focos)),rr=linReg(fire.map(d=>d.year),fire.map(d=>d.focos));$('#fireStats').innerHTML=pills([['Sen',`${sen>=0?'+':''}${fmt(sen,1)} focos/ano`],['MK τ',fmt(mk.tau,3)],['p',pfmt(mk.p)],['R²',fmt(rr.r2,3)]]);const early=mean(fire.filter(d=>d.year<=2015).map(d=>d.focos)),recent=mean(fire.filter(d=>d.year>=2016).map(d=>d.focos)),ratio=recent/early;$('#recentRatio').textContent=fmt(ratio,2)+'×';$('#recentText').textContent=`Média 2016–2024: ${fmt(recent,0)} focos/ano; 2003–2015: ${fmt(early,0)}. Isso não substitui um teste formal de mudança de regime.`}
function renderTypes(){const g={};types.forEach(d=>g[d.name]=(g[d.name]||0)+d.events);const a=Object.entries(g).sort((a,b)=>b[1]-a[1]),mx=Math.max(...a.map(x=>x[1]),1);$('#typeBars').innerHTML=a.map(([n,v])=>`<div class="type-row"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="width:${v/mx*100}%"></div></div><strong>${fmt(v,0)}</strong></div>`).join('')}
function trendSummary(key){const d=climate.filter(r=>Number.isFinite(r[key])),x=d.map(r=>r.year),y=d.map(r=>r[key]),mk=mannKendall(y),sen=senSlope(x,y),rr=linReg(x,y);return{key,n:d.length,mk,sen,rr,mean:mean(y)}}
function renderClimate(){if(!climate.length)return;const key=$('#climateVariable').value,m=META[key],d=climate.filter(r=>Number.isFinite(r[key])),s=trendSummary(key);$('#climateTitle').textContent=m.label;drawLine('#climateChart',d.map(r=>r.year),d.map(r=>r[key]),{trend:true,color:'#19756f'});$('#climateStats').innerHTML=pills([['Média',`${fmt(s.mean,1)} ${m.unit}`],['Sen',`${s.sen>=0?'+':''}${fmt(s.sen,3)} ${m.unit}/ano`],['MK τ',fmt(s.mk.tau,3)],['p',pfmt(s.mk.p)],['R²',fmt(s.rr.r2,3)],['n',String(s.n)]])}
function renderTrendTable(){if(!climate.length)return;const rows=Object.keys(META).map(k=>trendSummary(k));$('#trendTable tbody').innerHTML=rows.map(s=>{const m=META[s.key],sig=s.mk.p<.05,dir=s.sen>0?'aumento':s.sen<0?'redução':'estável',reading=sig?`${dir} significativo`:`${dir}, sem significância`;return `<tr><td>${m.label}</td><td>${s.sen>=0?'+':''}${fmt(s.sen,3)} ${m.unit}</td><td>${fmt(s.mk.tau,3)}</td><td>${pfmt(s.mk.p)}</td><td>${fmt(s.rr.r2,3)}</td><td class="${sig?'sig':'nonsig'}">${reading}</td></tr>`}).join('')}
function relationStats(){return Object.keys(META).map(key=>{const d=joined.filter(r=>Number.isFinite(r[key])&&Number.isFinite(r.focos)),x=d.map(r=>r[key]),y=d.map(r=>r.focos),r=pearson(x,y),rho=spearman(x,y),rr=linReg(x,y);return{key,n:d.length,r,rho,r2:rr.r2,slope:rr.slope}}).filter(z=>Number.isFinite(z.r)).sort((a,b)=>Math.abs(b.r)-Math.abs(a.r))}
function renderRelations(){if(!joined.length)return;const key=$('#scatterVariable').value,d=joined.filter(r=>Number.isFinite(r[key])),r=pearson(d.map(z=>z[key]),d.map(z=>z.focos)),rho=spearman(d.map(z=>z[key]),d.map(z=>z.focos)),rr=linReg(d.map(z=>z[key]),d.map(z=>z.focos));drawScatter('#scatterChart',d,key);$('#scatterStats').innerHTML=pills([['Pearson r',fmt(r,3)],['Spearman ρ',fmt(rho,3)],['R²',fmt(rr.r2,3)],['n',String(d.length)]]);const arr=relationStats();$('#relationRanking').innerHTML=`<div class="rank-list">${arr.map(z=>`<div class="rank-row"><span>${META[z.key].label}</span><div class="rank-track"><div class="rank-fill ${z.r<0?'neg':''}" style="width:${Math.abs(z.r)*100}%"></div></div><span class="rank-meta">r ${z.r>=0?'+':''}${fmt(z.r,2)}</span></div>`).join('')}</div>`;const best=arr[0];if(best){const sign=best.r<0?'inversa':'positiva',strength=Math.abs(best.r)>=.7?'forte':Math.abs(best.r)>=.5?'moderada a forte':Math.abs(best.r)>=.3?'moderada':'fraca';$('#relationFinding').innerHTML=`<strong>Principal relação observada:</strong> ${META[best.key].label} apresentou a maior associação linear com os focos entre as variáveis disponíveis (<strong>r = ${fmt(best.r,3)}</strong>; R² = ${fmt(best.r2,3)}; n = ${best.n}), uma relação ${sign} de magnitude ${strength}. É uma associação anual exploratória, não evidência isolada de causalidade.`;$('#strongestR').textContent=`r ${best.r>=0?'+':''}${fmt(best.r,2)}`;$('#strongestText').textContent=`Maior |r|: ${META[best.key].label.toLowerCase()} × focos, n=${best.n}.`}}
function renderMainTrendFinding(){const all=Object.keys(META).map(k=>trendSummary(k)),sig=all.filter(s=>s.mk.p<.05).sort((a,b)=>a.mk.p-b.mk.p);if(sig.length){const s=sig[0];$('#trendFinding').textContent=s.sen>0?'↑ significativo':'↓ significativo';$('#trendFindingText').textContent=`${META[s.key].label}: Sen ${s.sen>=0?'+':''}${fmt(s.sen,3)} ${META[s.key].unit}/ano, p=${pfmt(s.mk.p)}.`}else{const strongest=all.slice().sort((a,b)=>Math.abs(b.mk.tau)-Math.abs(a.mk.tau))[0];$('#trendFinding').textContent='sem p < 0,05';$('#trendFindingText').textContent=`Nenhuma variável climática apresentou tendência Mann–Kendall significativa no período disponível. Maior |τ|: ${META[strongest.key].label}, τ=${fmt(strongest.mk.tau,3)}.`}}
function corrColor(r){const a=Math.min(1,Math.abs(r)),alpha=.12+.48*a;return r<0?`rgba(223,95,54,${alpha})`:`rgba(25,117,111,${alpha})`}
function renderMatrix(){if(!joined.length)return;const vars=[['rain','Chuva'],['temp','T média'],['tmax','T máx'],['humidity','Umidade'],['heat_index','Índ. calor'],['logfire','log(Focos+1)']];let html='<table class="corr-table"><thead><tr><th></th>'+vars.map(v=>`<th>${v[1]}</th>`).join('')+'</tr></thead><tbody>';for(const [ki,li] of vars){html+=`<tr><th>${li}</th>`;for(const [kj] of vars){const r=pearson(joined.map(d=>d[ki]),joined.map(d=>d[kj]));html+=`<td style="background:${corrColor(r)}">${fmt(r,2)}</td>`}html+='</tr>'}html+='</tbody></table>';$('#corrMatrix').innerHTML=html}
function invertMatrix(A){const n=A.length,M=A.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let i=0;i<n;i++){let piv=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[piv][i]))piv=r;if(Math.abs(M[piv][i])<1e-12)return null;[M[i],M[piv]]=[M[piv],M[i]];const d=M[i][i];for(let j=0;j<2*n;j++)M[i][j]/=d;for(let r=0;r<n;r++)if(r!==i){const f=M[r][i];for(let j=0;j<2*n;j++)M[r][j]-=f*M[i][j]}}return M.map(r=>r.slice(n))}
function matVec(A,v){return A.map(r=>r.reduce((s,x,i)=>s+x*v[i],0))}
function multipleRegression(rows){const keys=['rain','tmax','humidity'],clean=rows.filter(r=>keys.every(k=>Number.isFinite(r[k]))&&Number.isFinite(r.logfire));if(clean.length<8)return null;const means=keys.map(k=>mean(clean.map(r=>r[k]))),sds=keys.map(k=>sd(clean.map(r=>r[k]))),X=clean.map(r=>[1,...keys.map((k,j)=>(r[k]-means[j])/(sds[j]||1))]),y=clean.map(r=>r.logfire),p=X[0].length,xtx=Array.from({length:p},()=>Array(p).fill(0)),xty=Array(p).fill(0);for(let i=0;i<clean.length;i++)for(let a=0;a<p;a++){xty[a]+=X[i][a]*y[i];for(let b=0;b<p;b++)xtx[a][b]+=X[i][a]*X[i][b]}const inv=invertMatrix(xtx);if(!inv)return null;const beta=matVec(inv,xty),pred=X.map(r=>r.reduce((s,v,j)=>s+v*beta[j],0)),ym=mean(y),sst=y.reduce((s,v)=>s+(v-ym)**2,0),sse=y.reduce((s,v,i)=>s+(v-pred[i])**2,0),r2=sst?1-sse/sst:NaN,adj=1-(1-r2)*(clean.length-1)/(clean.length-p);return{keys,beta,n:clean.length,r2,adj}}
function renderMulti(){const m=multipleRegression(joined);if(!m){$('#multiReg').innerHTML='<p class="muted">Dados insuficientes para o modelo.</p>';return}const max=Math.max(...m.beta.slice(1).map(Math.abs),.001);$('#multiReg').innerHTML=`<div class="model-kpis"><div><span>n</span><strong>${m.n}</strong></div><div><span>R²</span><strong>${fmt(m.r2,3)}</strong></div><div><span>R² ajust.</span><strong>${fmt(m.adj,3)}</strong></div></div><div class="coef-list">${m.keys.map((k,i)=>{const b=m.beta[i+1],pct=Math.abs(b)/max*100;return `<div class="coef"><span>${META[k].label}</span><strong>${b>=0?'+':''}${fmt(b,3)}</strong><div class="coef-bar"><i class="${b<0?'neg':''}" style="left:${b<0?100-pct:0}%;width:${pct}%"></i></div></div>`}).join('')}</div><p class="note">Betas são coeficientes com preditores padronizados. O modelo é exploratório; com cerca de duas décadas de sobreposição, deve ser interpretado com cautela.</p>`}
function jacobiEigen(A){const n=A.length,a=A.map(r=>r.slice()),V=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));for(let it=0;it<100*n*n;it++){let p=0,q=1,max=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(Math.abs(a[i][j])>max){max=Math.abs(a[i][j]);p=i;q=j}if(max<1e-10)break;const phi=.5*Math.atan2(2*a[p][q],a[q][q]-a[p][p]),c=Math.cos(phi),s=Math.sin(phi),app=c*c*a[p][p]-2*s*c*a[p][q]+s*s*a[q][q],aqq=s*s*a[p][p]+2*s*c*a[p][q]+c*c*a[q][q];for(let k=0;k<n;k++)if(k!==p&&k!==q){const akp=a[k][p],akq=a[k][q];a[k][p]=a[p][k]=c*akp-s*akq;a[k][q]=a[q][k]=s*akp+c*akq}a[p][p]=app;a[q][q]=aqq;a[p][q]=a[q][p]=0;for(let k=0;k<n;k++){const vkp=V[k][p],vkq=V[k][q];V[k][p]=c*vkp-s*vkq;V[k][q]=s*vkp+c*vkq}}const vals=Array.from({length:n},(_,i)=>a[i][i]),idx=vals.map((v,i)=>[v,i]).sort((a,b)=>b[0]-a[0]).map(x=>x[1]);return{values:idx.map(i=>vals[i]),vectors:V.map(row=>idx.map(i=>row[i]))}}
function pca(rows){const keys=['rain','temp','humidity','heat_index','logfire'],clean=rows.filter(r=>keys.every(k=>Number.isFinite(r[k])));if(clean.length<8)return null;const mu=keys.map(k=>mean(clean.map(r=>r[k]))),ss=keys.map(k=>sd(clean.map(r=>r[k]))),Z=clean.map(r=>keys.map((k,j)=>(r[k]-mu[j])/(ss[j]||1))),p=keys.length,C=Array.from({length:p},()=>Array(p).fill(0));for(let i=0;i<p;i++)for(let j=0;j<p;j++)C[i][j]=Z.reduce((s,row)=>s+row[i]*row[j],0)/(Z.length-1);const e=jacobiEigen(C),total=e.values.reduce((s,v)=>s+v,0),expl=e.values.map(v=>v/total*100),scores=Z.map((row,i)=>({year:clean[i].year,pc1:row.reduce((s,v,j)=>s+v*e.vectors[j][0],0),pc2:row.reduce((s,v,j)=>s+v*e.vectors[j][1],0)})),loads=keys.map((k,j)=>({key:k,pc1:e.vectors[j][0]*Math.sqrt(Math.max(e.values[0],0)),pc2:e.vectors[j][1]*Math.sqrt(Math.max(e.values[1],0))}));return{keys,expl,scores,loads,n:clean.length}}
function renderPCA(){const p=pca(joined);if(!p){$('#pcaLoadings').innerHTML='<p class="muted">Dados insuficientes para PCA.</p>';return}drawPCA(p.scores,p.expl[0],p.expl[1]);$('#pcaInfo').innerHTML=pills([['PC1',`${fmt(p.expl[0],1)}%`],['PC2',`${fmt(p.expl[1],1)}%`],['Acumulado',`${fmt(p.expl[0]+p.expl[1],1)}%`],['n',String(p.n)]]);$('#pcaLoadings').innerHTML=`<div class="loading-table"><table><thead><tr><th>Variável</th><th>PC1</th><th>PC2</th></tr></thead><tbody>${p.loads.map(l=>`<tr><td>${l.key==='logfire'?'log(Focos+1)':META[l.key].label}</td><td>${l.pc1>=0?'+':''}${fmt(l.pc1,3)}</td><td>${l.pc2>=0?'+':''}${fmt(l.pc2,3)}</td></tr>`).join('')}</tbody></table></div><p class="note">O sinal de um eixo da PCA é matematicamente arbitrário; interprete magnitudes e oposição entre cargas.</p>`}
function renderStatistics(){renderMatrix();renderMulti();renderPCA()}
function renderVisible(){if($('#visao').classList.contains('active')){renderFire();drawImpact()}if($('#clima').classList.contains('active'))renderClimate();if($('#relacoes').classList.contains('active'))renderRelations();if($('#estatistica').classList.contains('active'))renderStatistics()}
function setupTabs(){$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');requestAnimationFrame(()=>requestAnimationFrame(renderVisible))}))}
function setupControls(){$('#climateVariable').addEventListener('change',renderClimate);$('#scatterVariable').addEventListener('change',renderRelations);let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(renderVisible,160)})}
async function loadCore(){const [f,i,t]=await Promise.all([getCSV('data/focos_barao_2003_2024.csv'),getCSV('data/desastres_barao_1991_2024.csv'),getCSV('data/tipologias_barao.csv')]);fire=normalizeFire(f);impacts=normalizeImpacts(i);types=normalizeTypes(t);renderTypes();renderFire();drawImpact()}
async function loadClimate(){const notice=$('#climateNotice');try{const raw=await getCSV(CLIMATE_URL);monthly=normalizeMonthly(raw);if(!monthly.length)throw new Error('Nenhum registro do código 5101605 encontrado.');climate=aggregateAnnual(monthly);if(!climate.length)throw new Error('Não foi possível formar anos com pelo menos 10 meses.');joinAnnual();const years=climate.map(d=>d.year),min=Math.min(...years),max=Math.max(...years);notice.className='notice ok';notice.textContent=`Série climática carregada corretamente: ${monthly.length} meses • ${climate.length} anos • ${min}–${max}.`;$('#heroClimate').innerHTML=`<strong>${min}–${max}</strong><span>clima</span>`;$('#kpiClimate').innerHTML=`<span>Série climática</span><strong>${climate.length} anos</strong><small>${monthly.length} meses agregados</small>`;renderTrendTable();renderMainTrendFinding();renderRelations();renderStatistics();renderClimate()}catch(e){console.error(e);notice.className='notice error';notice.innerHTML=`<strong>Erro ao carregar o clima.</strong> Fogo e impactos continuam válidos. Detalhe: ${String(e.message||e)}`;$('#kpiClimate').innerHTML='<span>Série climática</span><strong>erro</strong><small>ver aviso na aba Clima</small>';$('#strongestText').textContent='A série climática não pôde ser carregada.';$('#trendFindingText').textContent='A série climática não pôde ser carregada.'}}
(async function init(){setupTabs();setupControls();try{await loadCore()}catch(e){console.error('Falha dados locais',e)}await loadClimate()})();