const MUNICIPIO = 'Barão de Melgaço';
const CODE = '5101605';
const CLIMATE_URL = 'https://raw.githubusercontent.com/ernandes-sobreira/clima-pantanal/main/data/clima_pantanal.csv';
const COLORS = {ink:'#0d1b2a', teal:'#1d766f', teal2:'#46a79c', fire:'#e75f32', gold:'#d8aa47', gray:'#9aa3aa', paper:'#f3f0e8'};
const climateMeta = {
  rain:{label:'Precipitação total', unit:'mm', short:'Precip.'},
  temp:{label:'Temperatura média', unit:'°C', short:'T média'},
  tmax:{label:'Temperatura máxima', unit:'°C', short:'T máxima'},
  tmin:{label:'Temperatura mínima', unit:'°C', short:'T mínima'},
  humidity:{label:'Umidade relativa média', unit:'%', short:'Umidade'},
  heat_index:{label:'Índice de calor médio', unit:'°C', short:'Índ. calor'}
};
let climate=[], fire=[], impacts=[], types=[], joined=[];
const charts={};

function splitCSVLine(line){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++;}else q=!q;}else if(c===','&&!q){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out;}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const h=splitCSVLine(lines[0]).map(x=>x.trim());return lines.slice(1).map(line=>{const v=splitCSVLine(line);return Object.fromEntries(h.map((k,i)=>[k,(v[i]??'').trim()]));});}
const num=v=>{if(v===null||v===undefined||v==='')return NaN;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:NaN;};
async function getCSV(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return parseCSV(await r.text());}
function pick(row,...keys){for(const k of keys){if(Object.prototype.hasOwnProperty.call(row,k)) return row[k];}return undefined;}
function normalizeClimate(rows){return rows.map(r=>({
 code:String(pick(r,'CD_MUN','codigo_ibge','COD_IBGE')??'').replace(/\.0$/,''),
 name:pick(r,'NM_MUN','municipio','MUNICIPIO'),year:num(pick(r,'ANO','ano','YEAR')),
 rain:num(pick(r,'PRECIPITACAO_TOTAL_MM')),temp:num(pick(r,'TEMPERATURA_MEDIA_C')),tmax:num(pick(r,'TEMPERATURA_MAX_C')),tmin:num(pick(r,'TEMPERATURA_MIN_C')),humidity:num(pick(r,'UMIDADE_RELATIVA_MEDIA_%')),heat_index:num(pick(r,'INDICE_CALOR_MEDIO'))
 })).filter(r=>r.code===CODE && Number.isFinite(r.year)).sort((a,b)=>a.year-b.year);}
function mean(a){const x=a.filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:NaN;}
function median(a){const x=a.filter(Number.isFinite).slice().sort((a,b)=>a-b);if(!x.length)return NaN;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2;}
function sd(a){const x=a.filter(Number.isFinite),m=mean(x);return x.length>1?Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1)):NaN;}
function pearson(a,b){const pairs=a.map((x,i)=>[x,b[i]]).filter(p=>p.every(Number.isFinite));if(pairs.length<3)return NaN;const x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]),mx=mean(x),my=mean(y);const n=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0);const dx=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)),dy=Math.sqrt(y.reduce((s,v)=>s+(v-my)**2,0));return dx&&dy?n/(dx*dy):NaN;}
function ranks(a){const idx=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),r=Array(a.length);let i=0;while(i<idx.length){let j=i;while(j+1<idx.length&&idx[j+1].v===idx[i].v)j++;const rr=(i+j+2)/2;for(let k=i;k<=j;k++)r[idx[k].i]=rr;i=j+1;}return r;}
function spearman(a,b){const pairs=a.map((x,i)=>[x,b[i]]).filter(p=>p.every(Number.isFinite));if(pairs.length<3)return NaN;return pearson(ranks(pairs.map(p=>p[0])),ranks(pairs.map(p=>p[1])));}
function linReg(x,y){const p=x.map((v,i)=>[v,y[i]]).filter(z=>z.every(Number.isFinite));if(p.length<2)return{slope:NaN,intercept:NaN,r2:NaN,n:p.length};const xs=p.map(z=>z[0]),ys=p.map(z=>z[1]),mx=mean(xs),my=mean(ys);const sxx=xs.reduce((s,v)=>s+(v-mx)**2,0),sxy=xs.reduce((s,v,i)=>s+(v-mx)*(ys[i]-my),0);const slope=sxy/sxx,intercept=my-slope*mx;const pred=xs.map(v=>intercept+slope*v);const sst=ys.reduce((s,v)=>s+(v-my)**2,0),sse=ys.reduce((s,v,i)=>s+(v-pred[i])**2,0);return{slope,intercept,r2:sst?1-sse/sst:0,n:p.length};}
function erf(x){const sign=x>=0?1:-1;x=Math.abs(x);const a1=.254829592,a2=-.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=.3275911,t=1/(1+p*x);return sign*(1-(((((a5*t+a4)*t)+a3)*t+a2)*t+a1)*t*Math.exp(-x*x));}
function normCDF(z){return .5*(1+erf(z/Math.sqrt(2)));}
function mannKendall(y){const v=y.filter(Number.isFinite),n=v.length;if(n<3)return{tau:NaN,p:NaN,S:NaN};let S=0;for(let i=0;i<n-1;i++)for(let j=i+1;j<n;j++)S+=Math.sign(v[j]-v[i]);const counts=new Map();v.forEach(x=>counts.set(x,(counts.get(x)||0)+1));const tie=[...counts.values()].reduce((s,t)=>s+t*(t-1)*(2*t+5),0);const varS=(n*(n-1)*(2*n+5)-tie)/18;const z=S>0?(S-1)/Math.sqrt(varS):S<0?(S+1)/Math.sqrt(varS):0;const p=2*(1-normCDF(Math.abs(z)));const tau=S/(n*(n-1)/2);return{S,tau,p,z};}
function senSlope(x,y){const p=x.map((v,i)=>[v,y[i]]).filter(z=>z.every(Number.isFinite)),s=[];for(let i=0;i<p.length-1;i++)for(let j=i+1;j<p.length;j++)if(p[j][0]!==p[i][0])s.push((p[j][1]-p[i][1])/(p[j][0]-p[i][0]));return median(s);}
function fmt(v,d=2){return Number.isFinite(v)?v.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';}
function pfmt(p){if(!Number.isFinite(p))return'—';if(p<.001)return'< 0,001';return fmt(p,3);}
function strength(r){const a=Math.abs(r);return a>=.7?'forte':a>=.5?'moderada-forte':a>=.3?'moderada':'fraca';}
function destroy(name){if(charts[name]){charts[name].destroy();delete charts[name];}}
function chartDefaults(){Chart.defaults.color='#50606c';Chart.defaults.font.family='Inter, system-ui, sans-serif';Chart.defaults.plugins.legend.labels.usePointStyle=true;Chart.defaults.plugins.legend.labels.boxWidth=8;}

function setupTabs(){document.querySelectorAll('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel-section').forEach(x=>x.classList.remove('active-section'));btn.classList.add('active');document.getElementById(btn.dataset.target).classList.add('active-section');setTimeout(()=>Object.values(charts).forEach(c=>c.resize()),30);}));}

function renderFire(){destroy('fire');const mk=mannKendall(fire.map(d=>d.focos_calor)),sen=senSlope(fire.map(d=>d.ano),fire.map(d=>d.focos_calor));document.getElementById('senFire').textContent=`${sen>=0?'+':''}${fmt(sen,1)}`;document.getElementById('mkFireText').textContent=`Mann–Kendall: τ = ${fmt(mk.tau,3)}, p = ${pfmt(mk.p)}. ${mk.p<.05?'Há tendência monotônica significativa.':'Não há tendência monotônica significativa.'}`;charts.fire=new Chart(document.getElementById('fireChart'),{type:'line',data:{labels:fire.map(d=>d.ano),datasets:[{label:'Focos',data:fire.map(d=>d.focos_calor),borderColor:COLORS.fire,backgroundColor:'rgba(231,95,50,.13)',fill:true,tension:.22,pointRadius:2.5,pointHoverRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,title:{display:true,text:'focos'}}}}});}
function renderImpacts(){destroy('impact');charts.impact=new Chart(document.getElementById('impactChart'),{data:{labels:impacts.map(d=>d.ano),datasets:[{type:'bar',label:'Eventos',data:impacts.map(d=>d.eventos_desastre),backgroundColor:'rgba(29,118,111,.72)',yAxisID:'y'},{type:'line',label:'Pessoas afetadas',data:impacts.map(d=>d.total_afetados),borderColor:COLORS.gold,backgroundColor:COLORS.gold,tension:.15,pointRadius:1.8,yAxisID:'y1'}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{grid:{display:false}},y:{beginAtZero:true,title:{display:true,text:'eventos'}},y1:{beginAtZero:true,position:'right',grid:{drawOnChartArea:false},title:{display:true,text:'afetados'}}}}});}
function renderTypes(){const grouped={};types.forEach(d=>{grouped[d.descricao_tipologia]=(grouped[d.descricao_tipologia]||0)+d.eventos;});const arr=Object.entries(grouped).sort((a,b)=>b[1]-a[1]),mx=Math.max(...arr.map(x=>x[1]));document.getElementById('typeBars').innerHTML=arr.map(([k,v])=>`<div class="type-row ${k.includes('Incêndio')?'fire-type':''}"><span>${k}</span><div class="bar-track"><div class="bar-fill" style="width:${v/mx*100}%"></div></div><strong>${v}</strong></div>`).join('');}

function climateValues(key){return climate.filter(d=>Number.isFinite(d[key]));}
function renderClimate(key=document.getElementById('climateVariable').value){const meta=climateMeta[key],d=climateValues(key);document.getElementById('climateChartTitle').textContent=meta.label;destroy('climate');const reg=linReg(d.map(x=>x.year),d.map(x=>x[key])),mk=mannKendall(d.map(x=>x[key])),sen=senSlope(d.map(x=>x.year),d.map(x=>x[key]));const line=d.map(x=>reg.intercept+reg.slope*x.year);charts.climate=new Chart(document.getElementById('climateChart'),{type:'line',data:{labels:d.map(x=>x.year),datasets:[{label:meta.label,data:d.map(x=>x[key]),borderColor:COLORS.teal,backgroundColor:'rgba(29,118,111,.11)',fill:true,tension:.2,pointRadius:1.7},{label:'Tendência linear',data:line,borderColor:COLORS.ink,borderDash:[7,5],pointRadius:0,borderWidth:1.5}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{grid:{display:false}},y:{title:{display:true,text:meta.unit}}}}});document.getElementById('climateStats').innerHTML=`<span class="stat-pill">Média <strong>${fmt(mean(d.map(x=>x[key])),1)} ${meta.unit}</strong></span><span class="stat-pill">Sen <strong>${sen>=0?'+':''}${fmt(sen,3)} ${meta.unit}/ano</strong></span><span class="stat-pill">Mann–Kendall τ <strong>${fmt(mk.tau,3)}</strong></span><span class="stat-pill">p <strong>${pfmt(mk.p)}</strong></span><span class="stat-pill">R² temporal <strong>${fmt(reg.r2,3)}</strong></span>`;}

function joinData(){const fm=new Map(fire.map(d=>[d.ano,d])),im=new Map(impacts.map(d=>[d.ano,d]));joined=climate.filter(c=>fm.has(c.year)).map(c=>({...c,...fm.get(c.year),...(im.get(c.year)||{eventos_desastre:0,total_afetados:0})}));}
function renderScatter(key=document.getElementById('scatterVariable').value){const meta=climateMeta[key],d=joined.filter(x=>Number.isFinite(x[key])&&Number.isFinite(x.focos_calor));if(!d.length)return;const x=d.map(z=>z[key]),y=d.map(z=>z.focos_calor),r=pearson(x,y),rho=spearman(x,y),reg=linReg(x,y);const xs=[Math.min(...x),Math.max(...x)];destroy('scatter');charts.scatter=new Chart(document.getElementById('scatterChart'),{type:'scatter',data:{datasets:[{label:'Ano',data:d.map(z=>({x:z[key],y:z.focos_calor,year:z.year})),backgroundColor:COLORS.fire,pointRadius:5},{label:'Regressão',type:'line',data:xs.map(v=>({x:v,y:reg.intercept+reg.slope*v})),borderColor:COLORS.ink,pointRadius:0,borderDash:[6,4]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:ctx=>ctx.raw.year?`${ctx.raw.year}: ${fmt(ctx.raw.x,1)} ${meta.unit} → ${ctx.raw.y} focos`:''}}},scales:{x:{title:{display:true,text:`${meta.label} (${meta.unit})`}},y:{beginAtZero:true,title:{display:true,text:'Focos de calor'}}}}});document.getElementById('scatterStats').innerHTML=`<span class="stat-pill">Pearson r <strong>${fmt(r,3)}</strong></span><span class="stat-pill">Spearman ρ <strong>${fmt(rho,3)}</strong></span><span class="stat-pill">R² <strong>${fmt(reg.r2,3)}</strong></span><span class="stat-pill">n <strong>${d.length}</strong></span><span class="stat-pill">força <strong>${strength(r)}</strong></span>`;}
function renderRanking(){const arr=Object.keys(climateMeta).map(key=>({key,r:pearson(joined.map(d=>d[key]),joined.map(d=>d.focos_calor)),rho:spearman(joined.map(d=>d[key]),joined.map(d=>d.focos_calor))})).filter(x=>Number.isFinite(x.r)).sort((a,b)=>Math.abs(b.r)-Math.abs(a.r));document.getElementById('correlationRanking').innerHTML=arr.map(x=>`<div class="rank-row"><span>${climateMeta[x.key].short}</span><div class="rank-track"><div class="rank-fill ${x.r<0?'neg':''}" style="width:${Math.abs(x.r)*100}%"></div></div><span class="rank-value">${x.r>0?'+':''}${fmt(x.r,2)}</span></div>`).join('');}

function corrColor(v){const a=Math.min(1,Math.abs(v)),alpha=.08+.34*a;return v<0?`rgba(231,95,50,${alpha})`:`rgba(29,118,111,${alpha})`;}
function renderCorrMatrix(){const vars=[['rain','Precip.'],['temp','T média'],['tmax','T máx.'],['humidity','Umidade'],['heat_index','Índ. calor'],['focos_calor','Focos'],['eventos_desastre','Eventos']];let html='<table><thead><tr><th></th>'+vars.map(v=>`<th>${v[1]}</th>`).join('')+'</tr></thead><tbody>';for(const [a,la] of vars){html+=`<tr><th>${la}</th>`;for(const [b] of vars){const r=pearson(joined.map(d=>d[a]),joined.map(d=>d[b]));html+=`<td class="corr-cell" style="background:${corrColor(r)}">${fmt(r,2)}</td>`;}html+='</tr>';}html+='</tbody></table>';document.getElementById('corrMatrix').innerHTML=html;}
function invert(A){const n=A.length,M=A.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[p][i]))p=r;if(Math.abs(M[p][i])<1e-12)return null;[M[i],M[p]]=[M[p],M[i]];const d=M[i][i];for(let j=0;j<2*n;j++)M[i][j]/=d;for(let r=0;r<n;r++)if(r!==i){const f=M[r][i];for(let j=0;j<2*n;j++)M[r][j]-=f*M[i][j];}}return M.map(r=>r.slice(n));}
function matMul(A,B){return A.map(r=>B[0].map((_,j)=>r.reduce((s,v,k)=>s+v*B[k][j],0)));}
function renderMultipleRegression(){const keys=['rain','tmax','humidity'],rows=joined.filter(d=>keys.every(k=>Number.isFinite(d[k]))&&Number.isFinite(d.focos_calor));if(rows.length<8)return;const statsObj=Object.fromEntries(keys.map(k=>[k,{m:mean(rows.map(d=>d[k])),s:sd(rows.map(d=>d[k]))}]));const X=rows.map(d=>[1,...keys.map(k=>(d[k]-statsObj[k].m)/statsObj[k].s)]),Y=rows.map(d=>[Math.log1p(d.focos_calor)]),Xt=X[0].map((_,j)=>X.map(r=>r[j])),inv=invert(matMul(Xt,X));if(!inv){document.getElementById('multiReg').innerHTML='<p>Modelo singular.</p>';return;}const beta=matMul(matMul(inv,Xt),Y).map(x=>x[0]),pred=X.map(r=>r.reduce((s,v,i)=>s+v*beta[i],0)),yv=Y.map(v=>v[0]),ym=mean(yv),sst=yv.reduce((s,v)=>s+(v-ym)**2,0),sse=yv.reduce((s,v,i)=>s+(v-pred[i])**2,0),r2=1-sse/sst,n=rows.length,p=keys.length,adj=1-(1-r2)*(n-1)/(n-p-1);document.getElementById('multiReg').innerHTML=`<div class="model-kpis"><div><span>R²</span><strong>${fmt(r2,3)}</strong></div><div><span>R² ajustado</span><strong>${fmt(adj,3)}</strong></div><div><span>n</span><strong>${n}</strong></div></div><p class="footnote">Resposta: log(1 + focos). Preditores padronizados (z-score); coeficientes indicam direção e efeito relativo dentro deste modelo exploratório.</p>${keys.map((k,i)=>`<div class="coef-row"><span>${climateMeta[k].label}</span><strong>${beta[i+1]>=0?'+':''}${fmt(beta[i+1],3)}</strong></div>`).join('')}`;}

function jacobi(A,maxIter=120){const n=A.length,V=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0)),D=A.map(r=>r.slice());for(let it=0;it<maxIter;it++){let p=0,q=1,m=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(Math.abs(D[i][j])>m){m=Math.abs(D[i][j]);p=i;q=j;}if(m<1e-10)break;const phi=.5*Math.atan2(2*D[p][q],D[q][q]-D[p][p]),c=Math.cos(phi),s=Math.sin(phi);for(let i=0;i<n;i++)if(i!==p&&i!==q){const dip=D[i][p],diq=D[i][q];D[i][p]=D[p][i]=c*dip-s*diq;D[i][q]=D[q][i]=s*dip+c*diq;}const app=D[p][p],aqq=D[q][q],apq=D[p][q];D[p][p]=c*c*app-2*s*c*apq+s*s*aqq;D[q][q]=s*s*app+2*s*c*apq+c*c*aqq;D[p][q]=D[q][p]=0;for(let i=0;i<n;i++){const vip=V[i][p],viq=V[i][q];V[i][p]=c*vip-s*viq;V[i][q]=s*vip+c*viq;}}const vals=Array.from({length:n},(_,i)=>D[i][i]),order=vals.map((v,i)=>({v,i})).sort((a,b)=>b.v-a.v);return{values:order.map(o=>o.v),vectors:V.map(r=>order.map(o=>r[o.i]))};}
function renderPCA(){const specs=[['rain','Precip.'],['tmax','T máx.'],['humidity','Umidade'],['heat_index','Índ. calor'],['focos_calor','Focos']],rows=joined.filter(d=>specs.every(([k])=>Number.isFinite(d[k])));if(rows.length<6)return;const means=specs.map(([k])=>mean(rows.map(d=>d[k]))),sds=specs.map(([k])=>sd(rows.map(d=>d[k]))),Z=rows.map(d=>specs.map(([k],j)=>(d[k]-means[j])/sds[j])),p=specs.length,C=Array.from({length:p},(_,i)=>Array.from({length:p},(_,j)=>Z.reduce((s,r)=>s+r[i]*r[j],0)/(Z.length-1))),eig=jacobi(C),total=eig.values.reduce((a,b)=>a+b,0),ev=eig.values.map(v=>v/total),scores=Z.map(r=>[r.reduce((s,v,i)=>s+v*eig.vectors[i][0],0),r.reduce((s,v,i)=>s+v*eig.vectors[i][1],0)]);destroy('pca');charts.pca=new Chart(document.getElementById('pcaChart'),{type:'scatter',data:{datasets:[{label:'Anos',data:scores.map((s,i)=>({x:s[0],y:s[1],year:rows[i].year})),backgroundColor:rows.map(r=>r.focos_calor>=1000?COLORS.fire:COLORS.teal),pointRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:ctx=>`${ctx.raw.year}: PC1 ${fmt(ctx.raw.x,2)}; PC2 ${fmt(ctx.raw.y,2)}`}},legend:{display:false}},scales:{x:{title:{display:true,text:`PC1 (${fmt(ev[0]*100,1)}%)`}},y:{title:{display:true,text:`PC2 (${fmt(ev[1]*100,1)}%)`}}}}});document.getElementById('pcaInfo').innerHTML=`<span class="stat-pill">PC1 <strong>${fmt(ev[0]*100,1)}%</strong></span><span class="stat-pill">PC2 <strong>${fmt(ev[1]*100,1)}%</strong></span><span class="stat-pill">acumulado <strong>${fmt((ev[0]+ev[1])*100,1)}%</strong></span><span class="stat-pill">n <strong>${rows.length}</strong></span>`;let html='<table><thead><tr><th>Variável</th><th>PC1</th><th>PC2</th></tr></thead><tbody>';specs.forEach(([k,l],i)=>{html+=`<tr><td>${l}</td><td>${fmt(eig.vectors[i][0],3)}</td><td>${fmt(eig.vectors[i][1],3)}</td></tr>`});html+='</tbody></table><p class="footnote">Sinal dos componentes pode inverter sem alterar a interpretação. Compare magnitudes absolutas das cargas.</p>';document.getElementById('pcaLoadings').innerHTML=html;}

function updateClimateMeta(){if(!climate.length)return;const y0=climate[0].year,y1=climate.at(-1).year;document.getElementById('climatePeriod').innerHTML=`<strong>${y0}–${y1}</strong><small>série climática</small>`;const hottest=climateValues('temp').slice().sort((a,b)=>b.temp-a.temp)[0];document.getElementById('kpiClimate').innerHTML=`<span>Maior T média</span><strong>${fmt(hottest?.temp,1)} °C</strong><small>${hottest?.year??'—'} • série climática</small>`;const n=document.getElementById('climateNotice');n.className='notice ok';n.textContent=`Série carregada: ${climate.length} anos municipais (${y0}–${y1}). As análises abaixo foram recalculadas agora.`;}
async function init(){chartDefaults();setupTabs();try{const [f,i,t]=await Promise.all([getCSV('data/focos_barao_2003_2024.csv'),getCSV('data/desastres_barao_1991_2024.csv'),getCSV('data/tipologias_barao.csv')]);fire=f.map(r=>({ano:num(r.ano),focos_calor:num(r.focos_calor),area_km2:num(r.area_km2),focos_por_km2:num(r.focos_por_km2)}));impacts=i.map(r=>({ano:num(r.ano),eventos_desastre:num(r.eventos_desastre),total_afetados:num(r.total_afetados)}));types=t.map(r=>({...r,eventos:num(r.eventos),total_afetados:num(r.total_afetados)}));renderFire();renderImpacts();renderTypes();}catch(e){console.error('Falha dados locais',e);}
try{climate=normalizeClimate(await getCSV(CLIMATE_URL));if(!climate.length)throw new Error('Nenhuma linha de Barão de Melgaço encontrada na base climática.');updateClimateMeta();joinData();renderClimate();renderScatter();renderRanking();renderCorrMatrix();renderMultipleRegression();renderPCA();}catch(e){console.error(e);const n=document.getElementById('climateNotice');n.className='notice error';n.textContent='A série climática externa não pôde ser carregada agora. Fogo e impactos continuam disponíveis. O painel tentará novamente no próximo acesso.';}
document.getElementById('climateVariable').addEventListener('change',e=>climate.length&&renderClimate(e.target.value));document.getElementById('scatterVariable').addEventListener('change',e=>joined.length&&renderScatter(e.target.value));}
window.addEventListener('DOMContentLoaded',init);
